services:
  starlink_exporter:
    image: docker.io/clarkzjw/starlink_exporter:latest
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    networks:
      - starlinkexporter
    hostname: starlinkexporter
    ports:
      - "9817:9817"
    env_file:
      - envfile

  prometheus:
    image: "docker.io/prom/prometheus:v2.37.9"
    restart: always
    networks:
      - starlinkexporter
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=3650d'
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
      - ./data/prometheus:/prometheus:Z

  grafana:
    image: "docker.io/grafana/grafana-oss:11.6.0"
    restart: always
    networks:
      - starlinkexporter
    hostname: grafana
    user: "root"
    ports:
      - "3000:3000"
    env_file:
      - envfile
    volumes:
      - ./data/grafana:/var/lib/grafana:Z
      - ./config/grafana/provisioning:/etc/grafana/provisioning/:rw,Z

  influxdb:
    image: "docker.io/library/influxdb:2.7.12"
    ports:
      - "8086:8086"
    restart: always
    networks:
      - starlinkexporter
    hostname: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb2:Z
      - ./config/influxdb:/etc/influxdb2:ro,Z
    env_file:
      - envfile

  telegraf:
    image: "docker.io/library/telegraf:1.34"
    restart: always
    networks:
      - starlinkexporter
    hostname: telegraf
    cap_add:
      - NET_RAW
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro,Z
    env_file:
      - envfile

networks:
  starlinkexporter:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2401:da80:1000:2::/64
