[[inputs.ping]]
  ## Hosts to send ping packets to.
  urls = ["ipinfo.io", "v6.ipinfo.io"]
  method = "native"

[[inputs.dns_query]]
  ## servers to query
  servers = ["192.168.1.1"]

# Output Configuration for telegraf agent
[[outputs.influxdb_v2]]	
  ## urls exp: http://127.0.0.1:8086
  urls = ["http://influxdb:8086"]

  ## Token for authentication.
  token = "$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "$DOCKER_INFLUXDB_INIT_ORG"

  ## Destination bucket to write into.
  bucket = "$DOCKER_INFLUXDB_INIT_BUCKET"

  insecure_skip_verify = true
